min_ply = 16
min_pieces = 4
max_eval = 8000
filter_tactical = true
filter_check = true
filter_castling = false
max_eval_incorrectness = 4294967295
random_fen_skipping = false
random_fen_skip_probability = 0.0
wld_filtered = false
wdl_model_params_a = [6.871_558_62, -39.652_263_91, 90.684_603_52, 170.669_963_64]
wdl_model_params_b = [
    -7.198_907_10,
    56.139_471_85,
    -139.910_911_83,
    182.810_074_27,
]
normalise_to_pawn_value = 229
wdl_heuristic_scale = 1.5